### ISSUE TITLE
Disappear 'activeClassName' with search params.

### ISSUE THREAD

**Issue by cr7parker** [nareshbhatia/mobx-state-router#63]
Hello. 
There is the next route:
  ```javascript
{
    name: RoutesName.USER_LIST,
    pattern: '/users'
  }
```

But when the query string is sent `/users?showDeleted=false`, the activeClassName flies off.

**Comment by nareshbhatia** [comment]
Hi @cr7parker, this issue has been fixed in version 5.0.0-beta.4. The reason you were facing this issue is that the test for determining if a link is active was too strict - the entire `RouterState` had to match, including params and queryParams. I have now relaxed the test to only check for routeName which covers 80% of the cases. In special cases, if your test for determining the active class is more complex, you can now pass a `isActive()` function to the link. See [here](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/components/RouterLink.tsx#L12-L20).

Please not that version 5 has a few breaking changes to simplify the APIs. You can find a change log [here](https://github.com/nareshbhatia/mobx-state-router/blob/master/CHANGELOG.md). Feedback welcome!
