### ISSUE TITLE
Why is rootStore a mandatory parameter?

### ISSUE THREAD

**Issue by Clee681** [nareshbhatia/mobx-state-router#68]
Hello!

Thanks for creating a wonderful library. I realize at this point it would be a breaking change to remove the `rootStore` argument of `RouterStore`, but I wanted to log that it seems to be _too_ opinionated of a requirement. Currently, all of my stores are in a simple object which I spread to mobx's `Provider` component (`<Provider stores={...stores}>`). This is convenient since I can inject the stores directly without having to pull the store one level deep from the `rootStore`.

Curious to hear your thoughts, and thanks again!

**Comment by nareshbhatia** [comment]
Hi @Clee681,

Glad that you are liking the library.

The idea of requiring a `rootStore` actually comes from the [best practices](https://mobx.js.org/best/store.html#combining-multiple-stores) described in the MobX documentation. The pattern has served me well - it allows multiple stores to be accessed from a single entry point. I am afraid that making a change at this point will be a huge disruption for hundreds of users. I understand that since you are using a different convention, it would be a slight inconvenience to you.

**Comment by nareshbhatia** [comment]
@Clee681, you will be glad to know that version 5 (currently in beta) implements your request. It's a major release and I am introducing a few minor breaking changes to clean up the API. `rootStore` is no longer a required parameter. Instead you can pass any number of options into the constructor. Please see [here](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/stores/RouterStore.ts#L48-L70). Let me know what you think.
