### ISSUE TITLE
routerState changes twice on transition

### ISSUE THREAD

**Issue by lukavuletic** [nareshbhatia/mobx-state-router#71]
Recently I have discovered that routerState changes twice on one transition. I have tested it on a completely fresh project (meaning I have created and installed only necessary things to reproduce the case) and on three different projects, all with different configuration. 
I have tried both observing and having a reaction on routerState, as well as debugging actual sourcecode through chrome dev tools.

Is there a specific reason as to why that happens, and if so, is there a way to react only to one change with ignoring the other one, while still having access to routerState as an object? Also routerState that I'm interested in is the one I am transitioning to.

**Comment by nareshbhatia** [comment]
Hi @lukavuletic, as far as I can tell, the routerState changes only once on one transition. The easiest way to confirm this is to put a console.log() in [RouterStore.setRouterState()](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/stores/RouterStore.ts#L96). This is the single location where the routerState is changed. After adding this console.log(), I tested with two sample apps: [mobx-shop](https://github.com/nareshbhatia/mobx-state-router/tree/master/examples/mobx-shop) and (animated-transitions)[https://github.com/nareshbhatia/mobx-state-router/tree/master/examples/animated-transitions] - I did not find any issues. One state change per transition. It could be that you are seeing this because of some re-renders outside of mobx-state-router.

Closing this for now. Feel free to reopen if you can prove otherwise.

**Comment by leoperria** [comment]
Hi, first of all thanks @nareshbhatia for this great project ! I'm starting to use mobx-state-router so maybe this is  red herring. I had  the exact same problem of @lukavuletic, basically I was using this link component:

```typescript
<RouterLink routeName="folder" params={{ folderId: 1 }} />   // <--- not folderId  is a number and not a string
```
and this was triggering the double transitions. So  I tried to debug those state transitions in `beforeEnter` hook and I noticed that when I clicked the link the hook was  called twice. The first time with `folderId`  as the number 1 and the second time as the string "1"

@nareshbhatia am I doing something  wrong ? thanks for your help
